### ISSUE TITLE
undefined locations map random to cities (DNSLOC / blue nodes)

### ISSUE THREAD

**Issue by Namsep** [emileaben/django-openipmap#17]
Have seen several traces in which there are several "?? undefined" locations that get mapped to a city and maybe receive a high confidence as the route is marked in blue.

**Comment by emileaben** [comment]
blue nodes are nodes with DNSLOC records (as explained in the online help on top right of the UI).
UI could be improved by, when showing the details for a single trace, to expose this information better (blue background and show the lat/lon for the location and/or do a guess by reverse geocoding the location for the lat/lon in the DNSLOC record).
