### ISSUE TITLE
Add https access to map tiles by removing http: string from sourcecode

### ISSUE THREAD

**Issue by mahtin** [emileaben/django-openipmap#7]
Presently map tiles are accessed via http vs https and yet the actual webpage is always https based.

```
function init_map() {
    map = L.map('map');

    var osmUrl='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    var osmAttrib='Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors';

    var mapqUrl='http://otile1.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.jpg';

    //var osm = new L.TileLayer(osmUrl, {attribution: osmAttrib});
    var osm = new L.TileLayer(mapqUrl, {attribution: osmAttrib});
    map.setView([20, 0], 3);
    map.addLayer(osm);
}
```

The following would be required in order to remove the browser errors when accessing the webpage [1].

```
    var osmUrl='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
```

```
    var mapqUrl='https://otile1-s.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.jpg';
```

Alternately; there could be additional code to select the URL for MapQuest (OpenStreetMap doesn't need code; it just needs less in the url string).

```
    var osmUrl='//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
```

```
    var mapqUrl = (document.location.protocol == 'https:' ?
            ''//otile1-s.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.jpg''
        :
            ''//otile1.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.jpg'';
```

There are references to https within the code.

```
 <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js'></script>
```

These could also be removed and just `//` used instead.

Finally (and this is being pedantic), the only other reference to http is in a comment:

```
// sprintf (from http://stackoverflow.com/questions/610406/javascript-equivalent-to-printf-string-format )
```

Which does not need editing; however also works with https. :)

[1] Found on http://developer.mapquest.com/widget/web/products/open/forums/-/message_boards/view_message/361015

**Comment by emileaben** [comment]
mapq URLs are now fetched over https
